version: '3.3'

volumes:
  mysqldata:
    
services:
  front_end:
    image: "node:alpine"
    build: ./services/front_end
    working_dir: /home/node/app
    volumes:
      - ${PWD}/volumes/front_end:/home/node/app:rw
    ports:
      - "3000:3000"
    environment:
      APP_MOUNT_ID: ${APP_MOUNT_ID}
      WEBSITE_NAME: ${WEBSITE_NAME}
    command: "npm run ${NPM_SCRIPT}"
  back_end:
    image: "node:alpine"
    build: ./services/back_end
    working_dir: /home/node/app
    volumes:
      - ${PWD}/volumes/back_end:/home/node/app:rw
    ports:
      - "8080:8080"
    depends_on:
      - db  
    command: "npm run ${BE_NPM_SCRIPT}"
    environment:
      SECRET_KEY: ${SECRET_KEY}
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./database:/tmp/database
      - mysqldata:/var/lib/mysql
    command: mysqld --init-file="/tmp/database/init.sql"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3001:3001"
    expose:
      - "3001"